Update cmi.yaml

diff --git a/.github/workflows/cmi.yaml b/.github/workflows/cmi.yaml
--- a/.github/workflows/cmi.yaml
+++ b/.github/workflows/cmi.yaml
@@ -17,8 +17,7 @@ jobs:
           nvm use 20.18.0
           npm install -g @dvcorg/cml
           export PATH="$HOME/.nvm/versions/node/v20.18.0/bin:$PATH"
-          ln -s $HOME/.nvm/versions/node/v20.18.0/bin/node /usr/bin/node
-
+          ln -sf $HOME/.nvm/versions/node/v20.18.0/bin/cml /usr/local/bin/cml
 
       - name: Train my model
         env:
@@ -26,13 +25,11 @@ jobs:
         run: |
           pip install -r requirements.txt
           python model.py
-
           echo "## Model Metrics" > report.md
           cat metrics.txt >> report.md
-
           echo "\n## Model Performance" >> report.md
           echo "Model performance metrics are on the plot below." >> report.md
-          
-          /github/home/.nvm/versions/node/v20.18.0/bin/cml-publish model_results.png --md >> report.md || echo "cml-publish failed"
-          /github/home/.nvm/versions/node/v20.18.0/bin/cml-send-comment report.md || echo "cml-send-comment failed"
+          cml publish model_results.png --md >> report.md || echo "cml-publish failed"
+          cml send-comment report.md || echo "cml-send-comment failed"
 
+      
